name: Publish
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      release_number: ${{steps.get_latest_release_number.outputs.release_tag}}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout xero-ruby repo
        uses: actions/checkout@v4
        with:
          repository: XeroAPI/xero-ruby
          path: xero-ruby

      - name: Fetch Latest release number
        id: get_latest_release_number
        run: |
            latest_version=$(gh release view --json tagName --jq '.tagName')
            echo "Latest release version is - $latest_version"
            echo "::set-output name=release_tag::$latest_version"
        working-directory: xero-ruby
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Set up Ruby environment
        uses: ruby/setup-ruby@v1
        with: 
          ruby-version: '3.2.0'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install
        working-directory: xero-ruby

      - name: Publish to Ruby
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: |
          gemspec_file=$(ls *.gemspec) 
          gem_file=$(gem build "$gemspec_file" | grep -o '[^ ]*\.gem')
          echo "$gem_file"
          gem push "$gem_file"
        working-directory: xero-ruby

  notify-slack-on-success:
    runs-on: ubuntu-latest
    needs: publish
    if: success()
    steps:
      - name: Checkout xero-ruby repo
        uses: actions/checkout@v4
        with:
          repository: XeroAPI/xero-ruby
          path: xero-ruby

      - name: Send slack notification on success
        uses: ./xero-ruby/.github/actions/notify-slack
        with:
          heading_text: "Publish job has succeeded !"
          alert_type: "thumbsup"
          job_status: "Success"
          XERO_SLACK_WEBHOOK_URL: ${{secrets.XERO_SLACK_WEBHOOK_URL}}
          job_url: "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
          button_type: "primary"
          package_version: ${{needs.publish.outputs.release_number}}
          repo_link: ${{github.server_url}}/${{github.repository}}

  notify-slack-on-failure:
      runs-on: ubuntu-latest
      needs: publish
      if: failure()
      steps:
        - name: Checkout xero-ruby repo
          uses: actions/checkout@v4
          with:
            repository: XeroAPI/xero-ruby
            path: xero-ruby
  
        - name: Send slack notification on failure
          uses: ./xero-ruby/.github/actions/notify-slack
          with:
            heading_text: "Publish job has failed !"
            alert_type: "alert"
            job_status: "Failed"
            XERO_SLACK_WEBHOOK_URL: ${{secrets.XERO_SLACK_WEBHOOK_URL}}
            job_url: "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
            button_type: "danger"
            package_version: ${{needs.publish.outputs.release_number}}
            repo_link: ${{github.server_url}}/${{github.repository}}